name: main

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo test

  staging:
    runs-on: ubuntu-latest
    steps:
      - run: echo stage

  manual-approval:
    environment: 'build-publish-env'
    runs-on: ubuntu-latest
    needs:
      - test
      - staging
    steps:
      - run: echo "Approved to Prod"

  prod:
    name: 'Deploy to Prod'
    needs: 
      - manual-approval
    runs-on: ubuntu-latest
    steps:
      - run: echo DEPLOYEDDDDDD
